# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 48c4b1ba9b31c882b809210a46148f11d0a10c77118c38b786174afce03ae42d058e60002693e0ed9643077999b49a2039133dcd5d004041d8bd9b3f078f1649

test:
  secret_key_base: 7c745b4567982a31bbffcaf2ea17bdaeae8763431400515f1dc5e44d945b60f817e0bd8700ebd037874e589692a7c05e8ea5baab5e86203d20424b74821ea4bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
